export const CustomModalStyles: ReactModal.Styles = {
  overlay: {
    backgroundColor: " rgba(0, 0, 0, 0.4)",
    width: "100%",
    height: "100vh",
    zIndex: "10",
    position: "fixed",
    top: "0",
    left: "0",
  },
  content: {
    height: "500px",
    position: "absolute",
    zIndex: "150",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    borderColor: "transparent",
    borderRadius: "10px",
    boxShadow: "2px 2px 2px rgba(0, 0, 0, 0.25)",
    backgroundColor: "transparent",
    justifyContent: "center",
    overflow: "hidden",
    padding: "0",
    minWidth: "350px",
    maxWidth: "500px",
  },
};
